### ISSUE TITLE
sollen wir die Quellen vor oder nach den Diskussionsfragen zeigen?

### ISSUE THREAD

**Issue by carolinebaer** [carolinebaer/Vortrag-soziale-Ungleichheit_Lebenserwartung#3]

**Comment by louisap12** [comment]
Das habe ich mich auch schon gefragt. Wahrscheinlich ist es besser sie vor den Diskussionsfragen kurz durchzugehen. Sonst gehen die Quellen vielleicht in der Diskussion unter. Sonst kannst du ja mal morgen gucken wie die anderen das gemacht haben 👍 :)
