### ISSUE TITLE
Änderung - Quellen 

### ISSUE THREAD

**Issue by louisap12** [carolinebaer/Vortrag-soziale-Ungleichheit_Lebenserwartung#7]
Ich habe eben ( wollte eigentlich nur einen pull-request machen :D )
folgendes geändert:

- Quellen an Grafiken ergänzt
- Quellen am ende ergänzt ( hoffe das zitieren ist so okay)
- Die Fazit Folienüberschriften in Lebenserwartung und Mortalität gegliedert

Ich hoffe das passt so :)

**Comment by carolinebaer** [comment]
hab alles übertragen, ergänze vlt noch die seitenzahlen im Paper.

Brauchen wir die Quelle des Symbolbilds da nochmal extra?
