### ISSUE TITLE
Tabellen okay in Präsentation ?

### ISSUE THREAD

**Issue by louisap12** [carolinebaer/Vortrag-soziale-Ungleichheit_Lebenserwartung#8]
Ich meine es wurde mal gesagt, dass Tabellen zu unübersichtlich für eine Präsentation wären.
Aber eigentlich ist die Tabelle recht interessant, weil da auch die gesunde Lebenserwartung erwähnt wird.
Vielleicht können wir sonst einen wichtigen teil umranden / hervorheben , damit man das besser überblicken kann. :)

**Comment by carolinebaer** [comment]
welcher Teil wäre das denn genau?  ; )
